Almost completely new zshrc
Added a bunch of comments, new package management stuff, git aliases and more...

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -1,87 +1,101 @@
-#
-#  ___ _
-# |_ _| |_ __ _ _   _   Someone once told me on reddit you can't rice macOS,
-#  | || __/ _` | | | |
-#  | || || (_| | |_| |  I showed him my dotfiles, never heard from him again.
-# |___|\__\__,_|\__, |
-#               |___/   (This actually happend)
+#  ___
+# |_ _| |_ __ _ _   _   
+#  | || __/ _` | | | |  github: https://github.com/itaysharir
+#  | || || (_| | |_| |  reddit: u/visible-pop-2576
+# |___|\__\__,_|\__, |  dotfiles: https://github.com/itaysharir/Dotfiles
+#               |___/  
 
-# p10k configuration
-if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
-  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
-fi
+### Export ###
+export TERM="xterm-256color"                          # proper colors
+export ZSH_THEME="archcraft"                          # Set oh-my-zsh theme
+export EDITOR='emacsclient -c'                        # set emacs as default editor
+export ZSH="$HOME/.oh-my-zsh"                         # declare a variable to omz path
 
-## Export
-# Proper colors
-export TERM="xterm-256color"
+# add stuff to $PATH
+export PATH=$PATH:/Users/itaysharir/.spicetify        # add spicetify to $PATH
+export PATH="$HOME/.emacs.d/bin:$PATH"                # Add doom executable to $PATH
+export PATH="/opt/homebrew/opt/sphinx-doc/bin:$PATH"  # add sphinx to $PATH
 
-# Add spicetify to path
-export PATH=$PATH:/Users/itaysharir/.spicetify
+# locale
+export LANG="en_US.UTF-8"           # configure LANG variable
+export LC_COLLATE="en_US.UTF-8"     # configure LC_COLLATE variable
+export LC_CTYPE="en_US.UTF-8"       # configure LC_CTYPE variable
+export LC_MESSAGES="en_US.UTF-8"    # configure LC_MESSAGES variable
+export LC_MONETARY="en_US.UTF-8"    # configure LC_MONTERAY variable
+export LC_NUMERIC="en_US.UTF-8"     # configure LC_NUMERIC variable
+export LC_TIME="en_US.UTF-8"        # configure LC_TIME variable
+export LC_CTYPE="en_US.UTF-8"       # configure LC_CTYPE variable
 
-# add omz to path
-export ZSH="$HOME/.oh-my-zsh"
+### Aliases ###
+# package management
+alias brewup='brew update && brew upgrade'                           # Update and upgrade homebrew
+alias portup='sudo port selfupdate && sudo port upgrade outdated'    # update macports
+alias allup='brewup && portup'                                       # Update all packages
 
-# proper locale settings
-export LANG="en_US.UTF-8"
-export LC_COLLATE="en_US.UTF-8"
-export LC_CTYPE="en_US.UTF-8"
-export LC_MESSAGES="en_US.UTF-8"
-export LC_MONETARY="en_US.UTF-8"
-export LC_NUMERIC="en_US.UTF-8"
-export LC_TIME="en_US.UTF-8"
-export LC_CTYPE=en_US.UTF-8
+# shorten commands
+# alias cle='clear && colorscript --exec elfman' # clear the screen quickly and draw colorscript
+alias cle='clear' # clear the screen quickly
+alias ne='neofetch' # run neofetch quickly
 
-## Set oh-my-zsh theme
-ZSH_THEME="spaceship" # set by `omz`
+# git
+alias addup='git add -u'        # add a file
+alias addall='git add .'        # add the whole directory
+alias branch='git branch'       # check branch
+alias clone='git clone'         # clone a repository
+alias commit='git commit -m'    # commit with a message
+alias fetch='git fetch'         # fetch details about a repository
+alias pull='git pull origin'    # "undo" a push
+alias push='git push origin'    # push changes
+alias stat='git status'         # view loocal repo status
 
-## Load oh-my-zsh plugins
+# make
+alias rootmakeins='sudo make install'    # make install with root privlages
+alias makeins='make install'             # make install
+alias rootmakedel='sudo make uninstall'  # make uninstall
+alias makedel='make uninstall'           # make uninstall with root privlages
+
+# source .zshrc
+alias src='source ~/.zshrc' # apply changes made in .zshrc without closing zsh
+
+# change default shell
+alias tobash='chsh -s /opt/homebrew/bin/bash && echo Now log out...'   # change shell to bash
+alias tozsh='chsh -s /bin/zsh && echo Now log out...'                  # change shell to zsh
+alias tofish='chsh -s /opt/homebrew/bin/fish && echo Now log out...'   # change shell to fish
+
+# emacs and doom emacs
+alias em="emacsclient -t"                         # launch an emacs client quickly in the terminal
+# alias emacs="emacsclient -c"                      # launch an emacs client quickly
+alias doomsync="~/.emacs.d/bin/doom sync"         # sync doom emacs plugins
+alias doomdoctor="~/.emacs.d/bin/doom doctor"     # check doom emacs for errors
+alias doomupgrade="~/.emacs.d/bin/doom upgrade"   # upgrade doom emacs
+alias doompurge="~/.emacs.d/bin/doom purge"       # purge plugins in doom emacs
+
+# shorten cd ../../../
+alias .1='cd ..'              # cd 1 directory up
+alias .2='cd ../..'           # cd 2 directories up
+alias .3='cd ../../..'        # cd 3 directories up
+alias .4='cd ../../../..'     # cd 4 directories up
+alias .5='cd ../../../../..'  # cd 5 directories up
+
+# when creating a directory, create all parent directories
+alias mkdir='mkdir -pv'
+
+# confrimations
+alias mv='mv -i' # confirm before overwriting a file with mv
+alias cp='cp -i' # confirm before overwriting a file with cp
+alias ln='ln -i' # confirm before overwriting a file with ln
+
+### tell omz which plugins to load ###
 plugins=(
   zsh-autosuggestions
 )
 
-## Load oh-my-zsh
-source $ZSH/oh-my-zsh.sh
-
-## Aliases
-# Update and upgrade homebrew
-alias brewup='brew update && brew upgrade'
-
-# Reboot without sudo
-alias reboot='sudo reboot'
-
-# clear the screen quickly
-alias cle='clear; colorscript --exec elfman'
-
-# neofetch = ne
-alias ne='neofetch'
-
-# Cd into ~/.config
-alias cdconf='cd ~/.config'
-
-# cd up all directories
-alias .1='cd ..'
-alias .2='cd ../..'
-alias .3='cd ../../..'
-alias .4='cd ../../../..'
-alias .5='cd ../../../../..'
-
-# mkdir create parent directories
-alias mkdir='mkdir -pv'
-
-# Confirmations
-alias mv='mv -i'
-alias cp='cp -i'
-alias rm='rm -i'
-alias ln='ln -i'
-
-# Rickroll
-alias rr='curl -s -L https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash'
-
-## Extract files
+### function to easily extract files ###
+# usage: ex <file>
 ex ()
 {
-    if [ -f "$1" ] ; then
-     case $1 in
+    if [ -f "$file" ] ; then
+     case $file in
        *.tar.bz2)   tar xjf $1   ;;
        *.tar.gz)    tar xzf $1   ;;
        *.bz2)       bunzip2 $1   ;;
@@ -96,18 +110,15 @@ ex ()
        *.deb)       ar x $1      ;;
        *.tar.xz)    tar xf $1    ;;
        *.tar.zst)   unzstd $1    ;;
-       *)           echo "'$1' cannot be extracted via ex()" ;;
+       *)           echo "'$file' cannot be extracted via ex()" ;;
      esac
    else
-     echo "'$1' is not a valid file"
+     echo "'$file' is not a valid file"
    fi
 }
 
-# Finzlize p10k
-[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
 
-## neofetch on startup
-# neofetch
-
-## colorscript on startup
-colorscript --exec elfman
+### startup ###
+bindkey -v                  # set vi mode
+source $ZSH/oh-my-zsh.sh    # run omz load script
+# colorscript --exec elfman   # colorscript on startup
